proj_obj = \
$(OUTD)/autogrp.o \
$(OUTD)/carve.o   \
$(OUTD)/cmd16m.o  \
$(OUTD)/cmdall.o  \
$(OUTD)/cmddos.o  \
$(OUTD)/cmdelf.o  \
$(OUTD)/cmdline.o \
$(OUTD)/cmdnov.o  \
$(OUTD)/cmdos2.o  \
$(OUTD)/cmdphar.o \
$(OUTD)/cmdqnx.o  \
$(OUTD)/cmdraw.o  \
$(OUTD)/cmdtable.o\
$(OUTD)/cmdutils.o\
$(OUTD)/dbgall.o  \
$(OUTD)/dbgcv.o   \
$(OUTD)/dbgdwarf.o\
$(OUTD)/dbginfo.o \
$(OUTD)/dbgstubs.o\
$(OUTD)/debug.o   \
$(OUTD)/distrib.o \
$(OUTD)/global.o  \
$(OUTD)/hash.o    \
$(OUTD)/impexp.o  \
$(OUTD)/libr.o    \
$(OUTD)/libsupp.o \
$(OUTD)/linkio.o  \
$(OUTD)/linkutil.o\
$(OUTD)/load16m.o \
$(OUTD)/loaddos.o \
$(OUTD)/loadelf.o \
$(OUTD)/loadelf2.o\
$(OUTD)/loadfile.o\
$(OUTD)/loadflat.o\
$(OUTD)/loadnov.o \
$(OUTD)/loados2.o \
$(OUTD)/loadpe.o  \
$(OUTD)/loadphar.o\
$(OUTD)/loadqnx.o \
$(OUTD)/loadraw.o \
$(OUTD)/lsymtab.o \
$(OUTD)/mapio.o   \
$(OUTD)/mem.o     \
$(OUTD)/mixcache.o\
$(OUTD)/msg.o     \
$(OUTD)/ntio.o    \
$(OUTD)/obj2supp.o\
$(OUTD)/objcache.o\
$(OUTD)/objcalc.o \
$(OUTD)/objfree.o \
$(OUTD)/objio.o   \
$(OUTD)/objnode.o \
$(OUTD)/objomf.o  \
$(OUTD)/objorl.o  \
$(OUTD)/objpass1.o\
$(OUTD)/objpass2.o\
$(OUTD)/objstrip.o\
$(OUTD)/oldcache.o\
$(OUTD)/omfreloc.o\
$(OUTD)/orlstubs.o\
$(OUTD)/overlays.o\
$(OUTD)/ovlsupp.o \
$(OUTD)/permdata.o\
$(OUTD)/posixio.o \
$(OUTD)/procfile.o\
$(OUTD)/reloc.o   \
$(OUTD)/ring.o    \
$(OUTD)/ring2.o   \
$(OUTD)/salloc.o  \
$(OUTD)/spillio.o \
$(OUTD)/strtab.o  \
$(OUTD)/symmem.o  \
$(OUTD)/symtrace.o\
$(OUTD)/toc.o     \
$(OUTD)/virtmem.o \
$(OUTD)/virtpage.o\
$(OUTD)/wcomdef.o \
$(OUTD)/wlink.o   \
$(OUTD)/wlnkmsg.o
