       $(OUTD)/orlentry.obj    $(OUTD)/orlflhnd.obj    $(OUTD)/orlhash.obj &
       $(OUTD)/omfload.obj     $(OUTD)/omfmunge.obj    $(OUTD)/omfentr.obj &
       $(OUTD)/omfflhn.obj     $(OUTD)/omfdrctv.obj  &
       $(OUTD)/elfentr.obj     $(OUTD)/elflwlv.obj     $(OUTD)/elfflhn.obj &
       $(OUTD)/elfload.obj   &
       $(OUTD)/coffentr.obj    $(OUTD)/cofflwlv.obj    $(OUTD)/coffflhn.obj &
       $(OUTD)/coffload.obj    $(OUTD)/coffimpl.obj
