wres_more_objs = \
    $(outd_wres)/loadres.o      $(outd_wres)/mropnewf.o    $(outd_wres)/rdlli.o    \
    $(outd_wres)/resaccel.o     $(outd_wres)/resbitmp.o    $(outd_wres)/resdiag.o  \
    $(outd_wres)/resfont.o      $(outd_wres)/resiccu.o     $(outd_wres)/resmenu.o  \
    $(outd_wres)/resnamor.o     $(outd_wres)/resraw.o      $(outd_wres)/resstr.o   \
    $(outd_wres)/restbar.o      $(outd_wres)/restell.o     $(outd_wres)/resver.o   \
    $(outd_wres)/rillia.o       $(outd_wres)/rillib.o      $(outd_wres)/ropenfrw.o \
    $(outd_wres)/rrlli.o        $(outd_wres)/wrauto.o      $(outd_wres)/wrchkwrf.o \
    $(outd_wres)/wrdelrs.o      $(outd_wres)/wresrtns.o    $(outd_wres)/wrfilein.o \
    $(outd_wres)/wrgetri.o      $(outd_wres)/wrgetti.o     $(outd_wres)/wrhidcmp.o \
    $(outd_wres)/wrhidfno.o     $(outd_wres)/wrhidfre.o    $(outd_wres)/wrhidfrn.o \
    $(outd_wres)/wrhidfrs.o     $(outd_wres)/wridfree.o    $(outd_wres)/wridnfst.o \
    $(outd_wres)/wridtnoo.o     $(outd_wres)/wridtonu.o    $(outd_wres)/wridtost.o \
    $(outd_wres)/wrihidf.o      $(outd_wres)/wrisempt.o    $(outd_wres)/wrislr.o   \
    $(outd_wres)/write.o        $(outd_wres)/wrmergdi.o    $(outd_wres)/wrnextrs.o \
    $(outd_wres)/wropnewf.o     $(outd_wres)/wrrfwrid.o    $(outd_wres)/wrrwrid.o  \
    $(outd_wres)/wrwritdi.o
