wres_core_objs = \
    $(outd_wres)/loadfind.o     $(outd_wres)/loadstr.o     $(outd_wres)/mrrdrh.o   \
    $(outd_wres)/ralliae.o      $(outd_wres)/rclosef.o     $(outd_wres)/rduint16.o \
    $(outd_wres)/rduint32.o     $(outd_wres)/rduint8.o     $(outd_wres)/resseek.o  \
    $(outd_wres)/ropenfro.o     $(outd_wres)/rrdstr.o      $(outd_wres)/rrnamoor.o \
    $(outd_wres)/varstr.o       $(outd_wres)/wraddres.o    $(outd_wres)/wrerror.o  \
    $(outd_wres)/wrfindrs.o     $(outd_wres)/wrfirres.o    $(outd_wres)/wrfree.o   \
    $(outd_wres)/wrfreedi.o     $(outd_wres)/wrgetli.o     $(outd_wres)/wridcmp.o  \
    $(outd_wres)/wridexby.o     $(outd_wres)/wridfnoo.o    $(outd_wres)/wridfrnu.o \
    $(outd_wres)/wridfrst.o     $(outd_wres)/wridnacm.o    $(outd_wres)/wriidfn.o  \
    $(outd_wres)/wrinitdi.o     $(outd_wres)/wriswrf.o     $(outd_wres)/wrreaddi.o \
    $(outd_wres)/wrrewrid.o     $(outd_wres)/wrrfrr.o      $(outd_wres)/wrrftr.o   \
    $(outd_wres)/wrrhr.o 
