    $(outd_wres)/loadres.obj      $(outd_wres)/mropnewf.obj    $(outd_wres)/rdlli.obj    &
    $(outd_wres)/resaccel.obj     $(outd_wres)/resbitmp.obj    $(outd_wres)/resdiag.obj  &
    $(outd_wres)/resfont.obj      $(outd_wres)/resiccu.obj     $(outd_wres)/resmenu.obj  &
    $(outd_wres)/resnamor.obj     $(outd_wres)/resraw.obj      $(outd_wres)/resstr.obj   &
    $(outd_wres)/restbar.obj      $(outd_wres)/restell.obj     $(outd_wres)/resver.obj   &
    $(outd_wres)/rillia.obj       $(outd_wres)/rillib.obj      $(outd_wres)/ropenfrw.obj &
    $(outd_wres)/rrlli.obj        $(outd_wres)/wrauto.obj      $(outd_wres)/wrchkwrf.obj &
    $(outd_wres)/wrdelrs.obj      $(outd_wres)/wresrtns.obj    $(outd_wres)/wrfilein.obj &
    $(outd_wres)/wrgetri.obj      $(outd_wres)/wrgetti.obj     $(outd_wres)/wrhidcmp.obj &
    $(outd_wres)/wrhidfno.obj     $(outd_wres)/wrhidfre.obj    $(outd_wres)/wrhidfrn.obj &
    $(outd_wres)/wrhidfrs.obj     $(outd_wres)/wridfree.obj    $(outd_wres)/wridnfst.obj &
    $(outd_wres)/wridtnoo.obj     $(outd_wres)/wridtonu.obj    $(outd_wres)/wridtost.obj &
    $(outd_wres)/wrihidf.obj      $(outd_wres)/wrisempt.obj    $(outd_wres)/wrislr.obj   &
    $(outd_wres)/write.obj        $(outd_wres)/wrmergdi.obj    $(outd_wres)/wrnextrs.obj &
    $(outd_wres)/wropnewf.obj     $(outd_wres)/wrrfwrid.obj    $(outd_wres)/wrrwrid.obj  &
    $(outd_wres)/wrwritdi.obj
