    $(outd_wres)/loadfind.obj     $(outd_wres)/loadstr.obj     $(outd_wres)/mrrdrh.obj   &
    $(outd_wres)/ralliae.obj      $(outd_wres)/rclosef.obj     $(outd_wres)/rduint16.obj &
    $(outd_wres)/rduint32.obj     $(outd_wres)/rduint8.obj     $(outd_wres)/resseek.obj  &
    $(outd_wres)/ropenfro.obj     $(outd_wres)/rrdstr.obj      $(outd_wres)/rrnamoor.obj &
    $(outd_wres)/varstr.obj       $(outd_wres)/wraddres.obj    $(outd_wres)/wrerror.obj  &
    $(outd_wres)/wrfindrs.obj     $(outd_wres)/wrfirres.obj    $(outd_wres)/wrfree.obj   &
    $(outd_wres)/wrfreedi.obj     $(outd_wres)/wrgetli.obj     $(outd_wres)/wridcmp.obj  &
    $(outd_wres)/wridexby.obj     $(outd_wres)/wridfnoo.obj    $(outd_wres)/wridfrnu.obj &
    $(outd_wres)/wridfrst.obj     $(outd_wres)/wridnacm.obj    $(outd_wres)/wriidfn.obj  &
    $(outd_wres)/wrinitdi.obj     $(outd_wres)/wriswrf.obj     $(outd_wres)/wrreaddi.obj &
    $(outd_wres)/wrrewrid.obj     $(outd_wres)/wrrfrr.obj      $(outd_wres)/wrrftr.obj   &
    $(outd_wres)/wrrhr.obj 
